config/routes.rb
Encorefurnishings::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'pages#home'
  resources :pages, :only => [:home, :about, :services, :contact]
  get '/home', to:'pages#home'
  get '/about', to:'pages#about'
  get '/services', to: 'pages#services'
  get '/contact', to: 'messages#new'
  resources :products, :only => [:index, :show]
  resources :messages, :only => [:new, :create]
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/message.rb
class Message
  include ActiveAttr::Model

  attribute :name
  attribute :email
  attribute :subject
  attribute :content

  validates_presence_of :name
  validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500
end

app/models/product.rb
class Product < ActiveRecord::Base

  monetize :price_cents, :allow_nil => true

  mount_uploader :image, ImageUploader

  before_save :destroy_image?

  def sold?
    self.sold == true
  end
  
  def image_delete
    @image_delete ||= "0"
  end

  def image_delete=(value)
    @image_delete = value
  end

  private
    def destroy_image?
      self.remove_image! if @image_delete == "1"
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      MessageMailer.new_message(@message).deliver
      redirect_to root_url, notice: "Thank you for contacting me. I will be in touch."
    else
      error_message = @message.errors.full_messages.to_sentence.downcase.capitalize
      redirect_to contact_path, notice: error_message + "!"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @products = Product.order("RANDOM()").limit(3)
  end

  def about
    @lindsay_image_url = "https://s3-us-west-2.amazonaws.com/encorefurnishings-assets/uploads/lindsay.jpg"
  end

  def services
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def create
    @product = Product.new(product_params)
  end
 
  def update
    @product = Product.find(params[:id])
    @product.update_attributes!(product_params)
  end

  def show
    @product = Product.find(params[:id])
  end
 
  private
    def product_params
      params.require(:product).permit(:title, :description, :price, :price_cents, :price_currency, :image)
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_facebook_actions.html.haml
%iframe{allowtransparency: "true", frameborder: "0", scrolling: "no", src: "//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fencorefurnishingsnashville&width&layout=button_count&action=like&show_faces=false&share=true&height=21&appId=1402788286655281", style: "border:none; overflow:hidden; height:21px;"}

app/views/layouts/_footer.html.haml
.footer
  &copy;2014 Encore Furnishings | (615) 988-0189 | encorefurnishingsnashville@gmail.com

app/views/layouts/_navigation_menu.html.haml
%nav
  .compressed
    %ul
      %li= link_to "Menu"
  .expanded
    %ul
      %li= link_to "About", about_path
      %li= link_to "Services", services_path
      %li= link_to "Products", products_path
      %li= link_to "Blog", 'http://parisavenuehouse.wordpress.com/', :target => '_blank'
      %li= link_to "Contact", contact_path

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/[if IE 9 ] <html class="ie9" lang="en">
/ [if (gt IE 9)|!(IE)]><!
%html{:lang => "en"}
  / <![endif]
  %head
    %meta{:charset => "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Encore Furnishings"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/custom.modernizr"
    = csrf_meta_tags
    = favicon_link_tag 'https://s3-us-west-2.amazonaws.com/encorefurnishings-assets/uploads/favicon.ico'

    = javascript_include_tag "application"

  %body

    #fb-root

    #flash_messages
      - flash.each do |name, msg|
        = content_tag :div, msg, class: name

    .row.title_row
      .main_title
        %h1= link_to "Encore Furnishings", home_path
      .top_footer
        %p= "(615) 988-0189"
        %p= "encorefurnishingsnashville@gmail.com"

    .row.navigation_row
      .facebook_actions.large-5.columns
        = render "layouts/facebook_actions"
      .navigation_menu.large-6.columns
        = render "layouts/navigation_menu"

    .row.content
      = yield

    .row
      = render "layouts/footer"

app/views/messages/new.html.haml
%h1 Contact
.contact_form
  = form_for @message do |f|
    .field
      = f.label :name
      %br
      = f.text_field :name
    .field
      = f.label :email
      %br
      = f.text_field :email
    .field
      = f.label :subject
      %br
      = f.text_field :subject, :value => params[:subject]
    .field
      = f.label :content, "Message"
      %br
      = f.text_area :content
    .actions= f.submit "Send Message", :class => "contact_form_submit_button", :value => "Send"

app/views/pages/about.html.haml
.about
  %h1 About
  = link_to image_tag(@lindsay_image_url), 'http://parisavenuehouse.wordpress.com/', :target => '_blank'
  %p My name is Lindsay. I live in the South where I write, make music, make homes and make friends. I have two rescue pugs named Nora and Manny and we all live in a 1910 house. Older is always better, in my opinion, and you will usually find me scouring Craigslist and/or the backwoods in search of treasures to restore. Encore Furnishings is my furniture restoration, painting and staining service in Nashville, TN.

app/views/pages/contact.html.haml
.contact
  %h1 Contact
  %p For more information, contact me at (615) 988-0189 or encorefurnishingsnashville@gmail.com.

app/views/pages/home.html.haml
.home_images.large-12.columns
  - for product in @products
    = link_to image_tag(product.image.url(:medium).to_s), product_path(product.id), :id => "#{product.title} medium"

app/views/pages/services.html.haml
.services
  %h1 Services
  %p Custom painting, staining and restoration of furniture of all kinds. From French Provincial to Mid-Century modern, I can transform and restore your furniture so it is better than new! Choose one of our pieces or bring a piece to be custom painted to your specifications.

app/views/products/index.html.haml
.products
  %h1 Products
  - for product in @products
    = link_to image_tag(product.image.url(:medium).to_s), product_path(product.id), :id => "#{product.title} medium"

app/views/products/show.html.haml
%div.product
  %h1= @product.title
  = image_tag(@product.image.url(:large).to_s, :id => "#{@product.title} large")
  %p= @product.description
  %p.status
    .price
      = ("$" + "#{@product.price}")
    - if @product.sold?
      .sold
        = "SOLD!"
    - else
      .interested
        = link_to "I'm interested!", contact_path(:subject => @product.title)

  .products_link
    = link_to "Back to Products", products_path